using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MultiPortUpload.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddBenchmarkRunsTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent: Die Tabelle kann bereits manuell in der Datenbank
            // angelegt worden sein. CREATE TABLE IF NOT EXISTS verhindert, dass
            // die Migration beim Start (Database.Migrate) gegen ein bestehendes
            // Schema fehlschlägt; auf einer frischen DB wird die Tabelle erzeugt.
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS public.benchmark_runs (
                    id            bigint generated by default as identity not null,
                    created_at    timestamp with time zone not null default now(),
                    description   text null,
                    runner_name   text null,
                    running_time  real null,
                    run_uuid      uuid not null default gen_random_uuid(),
                    constraint benchmark_runs_pkey primary key (id)
                );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS public.benchmark_runs;");
        }
    }
}
